version: "3.7"

services:
  web:
    image: nginx:1.19.3-alpine
    container_name: blog-web
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - blog-network

  api:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: blog-api
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - blog-network

  db:
    image: mariadb:10.2
    container_name: blog-db
    ports:
      - "3386:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - blog-db:/var/lib/mysql
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  blog-db:
    driver: local
