name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      run: |
        git fetch --all --unshallow
        git push https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/${{secrets.HEROKU_APP_NAME}}.git master -f

    - name: Heroku Run
      uses: michcio1234/heroku-run@0.1.1
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        command:
          composer install --optimize-autoloader --no-dev
          php artisan migrate:fresh --force
          php artisan db:seed --force
          php artisan passport:client --password --name=boilerplate --provider=users
          php artisan lighthouse:validate-schema
